name: Build Docker image

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/.dockerignore'
      - '**/Dockerfile'
      - '**/subsync/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: subsync:local
